services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
